Metrics/AbcSize:
  Max: 20
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false
Style/EmptyLinesAroundBlockBody:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
