Lint/InheritException:
  Enabled: false

Metrics/AbcSize:
  Max: 25
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false
Style/EmptyLinesAroundBlockBody:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/NegatedIf:
  Enabled: false
