Lint/InheritException:
  Enabled: false

Metrics/AbcSize:
  Max: 32
Metrics/CyclomaticComplexity:
  Max: 11
Metrics/PerceivedComplexity:
  Max: 11
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/NegatedIf:
  Enabled: false
