AllCops:
  TargetRubyVersion: 2.1

Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false

Lint/InheritException:
  Enabled: false

Metrics/AbcSize:
  Max: 32
Metrics/CyclomaticComplexity:
  Max: 12
Metrics/PerceivedComplexity:
  Max: 12
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 25

Style/CommentedKeyword:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/InverseMethods:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/NegatedIf:
  Enabled: false
